import type { CuratedPalette } from "@/types";

export const curatedPalettes: CuratedPalette[] = [
  {
    id: "desert-gold",
    name: "Desert Sand & Gold",
    description: "Warm, regal tones inspired by Arabian heritage and desert landscapes",
    colors: ["#C8A45C", "#E8D5A3", "#8B6914", "#F5EDD6", "#3D2E0A"],
    preview: {
      primary: "#C8A45C",
      secondary: "#8B6914",
      accent: "#E8D5A3",
      background: "#FEFCF7",
      surface: "#FFF9ED",
    },
  },
  {
    id: "deep-teal",
    name: "Deep Blue & Teal",
    description: "Professional and trustworthy, ideal for government and enterprise",
    colors: ["#0A6E8A", "#0D3B66", "#14B8A6", "#E0F7FA", "#072A40"],
    preview: {
      primary: "#0A6E8A",
      secondary: "#0D3B66",
      accent: "#14B8A6",
      background: "#F8FDFE",
      surface: "#E8F6F8",
    },
  },
  {
    id: "emerald-slate",
    name: "Emerald & Slate",
    description: "Sophisticated and balanced, works across industries",
    colors: ["#10B981", "#1E293B", "#6EE7B7", "#F0FDF4", "#0F172A"],
    preview: {
      primary: "#10B981",
      secondary: "#1E293B",
      accent: "#6EE7B7",
      background: "#FAFDFB",
      surface: "#F0FDF4",
    },
  },
  {
    id: "plum-rose",
    name: "Plum & Rose",
    description: "Premium and elegant, perfect for hospitality and lifestyle brands",
    colors: ["#7C3AED", "#EC4899", "#C084FC", "#FAF5FF", "#4C1D95"],
    preview: {
      primary: "#7C3AED",
      secondary: "#EC4899",
      accent: "#C084FC",
      background: "#FDFAFE",
      surface: "#FAF5FF",
    },
  },
  {
    id: "neutral-electric",
    name: "Neutral & Electric",
    description: "Modern and tech-forward with sharp accent energy",
    colors: ["#3B82F6", "#1F2937", "#60A5FA", "#F8FAFC", "#111827"],
    preview: {
      primary: "#3B82F6",
      secondary: "#1F2937",
      accent: "#60A5FA",
      background: "#F9FAFB",
      surface: "#F1F5F9",
    },
  },
  {
    id: "coral-sand",
    name: "Coral & Sand",
    description: "Warm and inviting, great for hospitality, travel, and lifestyle",
    colors: ["#F97316", "#FDBA74", "#EA580C", "#FFF7ED", "#7C2D12"],
    preview: {
      primary: "#F97316",
      secondary: "#EA580C",
      accent: "#FDBA74",
      background: "#FFFBF5",
      surface: "#FFF7ED",
    },
  },
  {
    id: "midnight-indigo",
    name: "Midnight Indigo",
    description: "Deep and authoritative, perfect for fintech and enterprise dashboards",
    colors: ["#6366F1", "#312E81", "#818CF8", "#EEF2FF", "#1E1B4B"],
    preview: {
      primary: "#6366F1",
      secondary: "#312E81",
      accent: "#818CF8",
      background: "#F5F5FF",
      surface: "#EEF2FF",
    },
  },
  {
    id: "forest-moss",
    name: "Forest & Moss",
    description: "Natural and grounded, ideal for sustainability and agriculture",
    colors: ["#16A34A", "#166534", "#86EFAC", "#F0FDF4", "#052E16"],
    preview: {
      primary: "#16A34A",
      secondary: "#166534",
      accent: "#86EFAC",
      background: "#F7FEF9",
      surface: "#F0FDF4",
    },
  },
  {
    id: "ruby-charcoal",
    name: "Ruby & Charcoal",
    description: "Bold and high-contrast, excellent for media and news platforms",
    colors: ["#DC2626", "#1C1917", "#FCA5A5", "#FEF2F2", "#450A0A"],
    preview: {
      primary: "#DC2626",
      secondary: "#1C1917",
      accent: "#FCA5A5",
      background: "#FEFAFA",
      surface: "#FEF2F2",
    },
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    description: "Calm and refreshing, works well for healthcare and wellness",
    colors: ["#0EA5E9", "#0369A1", "#7DD3FC", "#F0F9FF", "#082F49"],
    preview: {
      primary: "#0EA5E9",
      secondary: "#0369A1",
      accent: "#7DD3FC",
      background: "#F5FBFF",
      surface: "#F0F9FF",
    },
  },
  {
    id: "amber-earth",
    name: "Amber & Earth",
    description: "Rich and warm, suited for construction, real estate, and logistics",
    colors: ["#D97706", "#92400E", "#FCD34D", "#FFFBEB", "#451A03"],
    preview: {
      primary: "#D97706",
      secondary: "#92400E",
      accent: "#FCD34D",
      background: "#FFFDF5",
      surface: "#FFFBEB",
    },
  },
  {
    id: "lavender-grey",
    name: "Lavender & Grey",
    description: "Soft and modern, great for SaaS, productivity, and creative tools",
    colors: ["#8B5CF6", "#6B7280", "#C4B5FD", "#F5F3FF", "#374151"],
    preview: {
      primary: "#8B5CF6",
      secondary: "#6B7280",
      accent: "#C4B5FD",
      background: "#FAFAFF",
      surface: "#F5F3FF",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold & Cream",
    description: "Luxurious and refined, ideal for beauty, fashion, and premium brands",
    colors: ["#E11D48", "#BE185D", "#FDA4AF", "#FFF1F2", "#881337"],
    preview: {
      primary: "#E11D48",
      secondary: "#BE185D",
      accent: "#FDA4AF",
      background: "#FFFBFC",
      surface: "#FFF1F2",
    },
  },
  {
    id: "arctic-steel",
    name: "Arctic & Steel",
    description: "Clean and industrial, fits manufacturing, engineering, and tech",
    colors: ["#64748B", "#334155", "#94A3B8", "#F8FAFC", "#0F172A"],
    preview: {
      primary: "#64748B",
      secondary: "#334155",
      accent: "#94A3B8",
      background: "#F9FAFB",
      surface: "#F8FAFC",
    },
  },
  {
    id: "citrus-pop",
    name: "Citrus Pop",
    description: "Vibrant and energetic, perfect for food, social, and youth brands",
    colors: ["#EAB308", "#CA8A04", "#FDE047", "#FEFCE8", "#713F12"],
    preview: {
      primary: "#EAB308",
      secondary: "#CA8A04",
      accent: "#FDE047",
      background: "#FFFEF5",
      surface: "#FEFCE8",
    },
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    description: "Futuristic and tech-forward, great for AI, gaming, and Web3",
    colors: ["#06B6D4", "#0E7490", "#22D3EE", "#ECFEFF", "#164E63"],
    preview: {
      primary: "#06B6D4",
      secondary: "#0E7490",
      accent: "#22D3EE",
      background: "#F5FEFF",
      surface: "#ECFEFF",
    },
  },
];
