import type { TypographyPack } from "@/types";

export const typographyPacks: TypographyPack[] = [
  {
    id: "clean-sans",
    name: "Clean Sans",
    description: "Versatile and neutral — works for everything from dashboards to portals",
    headingFont: "Inter",
    bodyFont: "Inter",
    arabicHeadingFont: "Noto Sans Arabic",
    arabicBodyFont: "Noto Sans Arabic",
    sampleHeading: "Welcome to your workspace",
    sampleBody: "Manage your projects, track progress, and collaborate with your team in one place.",
    sampleArabicHeading: "مرحباً بك في مساحة العمل",
    sampleArabicBody: "إدارة مشاريعك، تتبع التقدم، والتعاون مع فريقك في مكان واحد.",
  },
  {
    id: "premium-modern",
    name: "Premium Modern",
    description: "Refined and contemporary — elevates brand perception",
    headingFont: "DM Sans",
    bodyFont: "DM Sans",
    arabicHeadingFont: "IBM Plex Sans Arabic",
    arabicBodyFont: "IBM Plex Sans Arabic",
    sampleHeading: "Elevate your experience",
    sampleBody: "A refined platform built for teams who demand quality and precision in every interaction.",
    sampleArabicHeading: "ارتقِ بتجربتك",
    sampleArabicBody: "منصة متقدمة مصممة للفرق التي تطلب الجودة والدقة في كل تفاعل.",
  },
  {
    id: "formal-institutional",
    name: "Formal Institutional",
    description: "Authoritative and structured — built for trust and governance",
    headingFont: "Source Sans 3",
    bodyFont: "Source Sans 3",
    arabicHeadingFont: "Noto Kufi Arabic",
    arabicBodyFont: "Noto Sans Arabic",
    sampleHeading: "Official Services Portal",
    sampleBody: "Access government services, submit requests, and track application status securely.",
    sampleArabicHeading: "بوابة الخدمات الرسمية",
    sampleArabicBody: "الوصول إلى الخدمات الحكومية، تقديم الطلبات، وتتبع حالة التطبيقات بأمان.",
  },
  {
    id: "friendly-rounded",
    name: "Friendly Rounded",
    description: "Warm and approachable — ideal for education and HR portals",
    headingFont: "Nunito",
    bodyFont: "Nunito",
    arabicHeadingFont: "Tajawal",
    arabicBodyFont: "Tajawal",
    sampleHeading: "Start learning today",
    sampleBody: "Explore courses, connect with instructors, and build new skills at your own pace.",
    sampleArabicHeading: "ابدأ التعلم اليوم",
    sampleArabicBody: "استكشف الدورات، تواصل مع المدربين، وابنِ مهارات جديدة بالسرعة التي تناسبك.",
  },
  {
    id: "bold-product",
    name: "Bold Product UI",
    description: "Strong and confident — modern product and startup feel",
    headingFont: "Manrope",
    bodyFont: "Inter",
    arabicHeadingFont: "IBM Plex Sans Arabic",
    arabicBodyFont: "Noto Sans Arabic",
    sampleHeading: "Ship faster, build better",
    sampleBody: "The all-in-one toolkit for teams building the next generation of digital products.",
    sampleArabicHeading: "أطلق أسرع، ابنِ أفضل",
    sampleArabicBody: "مجموعة الأدوات المتكاملة للفرق التي تبني الجيل القادم من المنتجات الرقمية.",
  },
  {
    id: "compact-dashboard",
    name: "Compact Dashboard",
    description: "Dense and efficient — optimized for data-heavy interfaces",
    headingFont: "IBM Plex Sans",
    bodyFont: "IBM Plex Sans",
    arabicHeadingFont: "IBM Plex Sans Arabic",
    arabicBodyFont: "IBM Plex Sans Arabic",
    sampleHeading: "Operations Overview",
    sampleBody: "Monitor performance metrics, resource utilization, and system health in real-time.",
    sampleArabicHeading: "نظرة عامة على العمليات",
    sampleArabicBody: "مراقبة مقاييس الأداء، استخدام الموارد، وصحة النظام في الوقت الفعلي.",
  },
];
